# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build --if-present

      - name: Install Playwright
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npm run test

      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      - name: Run Jest tests
        run: npm run jest -- --json --coverage

      - name: Include missing packages
        run: |
          mkdir -p ./build/node_modules/snarkdown
          mkdir -p ./build/node_modules/cookie
          cp -r ./node_modules/snarkdown/* ./build/node_modules/snarkdown/
          cp -r ./node_modules/cookie/* ./build/node_modules/cookie/

      #   - name: Upload artifact for deployment job
      #     uses: actions/upload-artifact@v2
      #     with:
      #       name: node-app
      #       path: build/

      # deploy:
      #   runs-on: ubuntu-latest
      #   needs: build
      #   environment:
      #     name: 'production'
      #     url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

      #   steps:
      #   - name: Download artifact from build job
      #     uses: actions/download-artifact@v2
      #     with:
      #       name: node-app

      - name: Deploy application
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.APPSERVICE_NAME }}
          publish-profile: ${{ secrets.APPSERVICE_PUBLISHPROFILE }}
          package: ./build
